[dotnet]
sdk = "10.0.100"
runtime = "10.0.0"

# dotnâ€˜t support define multiple solution in one toml
[sln]
name = "dotnet"

# dotnet.projects equals csproj
[[csprojs]]
name = ""
include = ""
links = [

]

[[vcprojs]]
name = ""
include = ""
links = [

]

[cmake]
version = "xxx"

[[cmake.lib]]

[cmake.bin]